site_name: Airss Documentation
site_author: Lyz
site_url: https://lyz-code.github.io/airss-docs
nav:
  - Introduction: 'index.md'
  - Downloader: 'downloader/downloader.md'

plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  custom_dir: "theme"
  logo: "images/logo.png"
  palette:
    primary: 'blue grey'
    accent: 'light blue'

extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/links.css'
